apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/leon-viktor/catalog-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/leon-viktor/catalog-service
  newTag: e2c5e3680c4dfabc02c23ccc35e68a7a4e9dec31

replicas:
- count: 2
  name: catalog-service
