apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/leon-viktor/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/leon-viktor/order-service
  newTag: 1e3ec5531e4f4780191b36378ad8f18d61361861

replicas:
- count: 1
  name: order-service
